spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: FootGamers
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/foot_gamers
  jpa:
    hibernate:
      ddl-auto: create-drop